apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-orchestra.fullname" . }}-controller
  labels:
    {{- include "hume-orchestra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.controller.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hume-orchestra.fullname" . }}-controller
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-orchestra.fullname" . }}-worker
  labels:
    {{- include "hume-orchestra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.worker.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hume-orchestra.fullname" . }}-sts
