image: docker.graphaware.com/mirror/debian:stable-slim

stages:
  - lint
  - upload

lint-chart:
  state: lint
  tags:
    - graphaware
    - k8s
  image: alpine/helm:3.13.0
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip install pyyaml
  script:
    - helm template -f ./_tests/metrics-enabled.yml hume-helm > ./_tests/metrics-enabled-out.yml
    - python3 ./_tests/verify_labels.py

upload-chart:
  stage: upload
  tags:
    - k8s
    - graphaware
  script:
    - apt update && apt install -y curl git
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 &&  chmod 700 get_helm.sh
    - ./get_helm.sh
    - export HARBOR_USERNAME='robot$imagepull-secret-shared'
    - helm lint hume-alerting
    - helm dependency update hume-alerting
    - helm template hume-alerting -f hume-alerting/values.yaml
    - helm package hume-alerting
    - helm registry login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD docker.graphaware.com/public
    - helm push hume-alerting-*.tgz oci://docker.graphaware.com/public
    - rm -f hume-alerting-*.tgz
    - helm lint hume-helm
    - helm dependency update hume-helm
    - helm template hume-helm -f hume-helm/values.yaml
    - helm package hume-helm
    - helm push hume-*.tgz oci://docker.graphaware.com/public
    - helm registry logout docker.graphaware.com/public
  only:
    - main
    - tags
    - /^support/.*$/