{{- if eq .Values.humeMessagingProvider "azure-servicebus-topics" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-alerting.fullname" . }}-azure-sb-configmap
data:
  azure.servicebus.connection.string: {{ required "A valid Azure Service Bus connection string required" .Values.azure.serviceBus.connection_string | quote }}
  azure.servicebus.subscription.id: {{ required "A valid Azure Service Bus connection subscription required" .Values.azure.serviceBus.subscription_id | quote }}
  azure.servicebus.topics.names.scheduler: {{ .Values.azure.serviceBus.topics_names_scheduler | quote }}
  azure.servicebus.topics.names.action: {{ .Values.azure.serviceBus.topics_names_action | quote }}
  azure.servicebus.topics.names.notification: {{ .Values.azure.serviceBus.topics_names_notification | quote }}
  azure.servicebus.topics.names.feedback: {{ .Values.azure.serviceBus.topics_names_feedback | quote }}
  azure.servicebus.topics.names.operator-metrics: {{ .Values.azure.serviceBus.topics_names_operator_metrics | quote }}
  azure.servicebus.topics.names.dryRunRequest: {{ .Values.azure.serviceBus.topics_names_dryRunRequest | quote }}
  azure.servicebus.topics.names.dryRunResult: {{ .Values.azure.serviceBus.topics_names_dryRunResult }}
{{- end }}
