apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hume-alerting.fullname" . }}-controller
  labels:
    {{- include "hume-alerting.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.controller.deployment.replicas | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "hume-alerting.fullname" . }}-controller
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "alerting-controller-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "hume-alerting.selectorLabels" . | nindent 8 }}
        app: {{ include "hume-alerting.fullname" . }}-controller
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hume-alerting.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "hume-alerting.fullname" . }}-controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.humeAlertingControllerBaseRepository }}{{ .Values.controller.image.name }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: metrics
              containerPort: 7001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "hume-alerting.fullname" . }}-controller-configmap
            {{- if .Values.controller.extraSecrets }}
            {{- range .Values.controller.extraSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            - configMapRef:
            {{- if eq .Values.humeMessagingProvider "kafka" }}
                name: {{ include "hume-alerting.fullname" . }}-kafka-configmap
            {{- else if eq .Values.humeMessagingProvider "azure-servicebus-topics" }}
                name: {{ include "hume-alerting.fullname" . }}-azure-sb-configmap
            {{- end }}
          env:
            {{- with .Values.controller.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if not .Values.postgresqlAlertingController.enabled }}
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.customAlertingControllerPostgresql.global.postgresql.secretRef.existingSecret }}
                  key: {{ .Values.customAlertingControllerPostgresql.global.postgresql.secretRef.passwordSecretKey }}
            {{- end }}
          livenessProbe:
             httpGet:
               path: /actuator/health
               port: metrics
             initialDelaySeconds: 20
             periodSeconds: 20
          readinessProbe:
             httpGet:
               path: /actuator/health
               port: metrics
             failureThreshold: 10
             initialDelaySeconds: 20
             periodSeconds: 20
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}