apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-alerting.fullname" . }}-controller
  labels:
    {{- include "hume-alerting.labels" . | nindent 4 }}
    app.kubernetes.io/component: hume-alerting-controller
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: hume-alerting-controller
    {{- include "hume-alerting.selectorLabels" . | nindent 4 }}
---
{{- if .Values.controller.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-alerting.fullname" . }}-controller-metrics
  labels:
    {{- include "hume-alerting.labels" . | nindent 4 }}
    app.kubernetes.io/component: alerting-controller-metrics
spec:
  type: {{ .Values.controller.metrics.service.type }}
  ports:
    - port: {{ .Values.controller.metrics.service.port }}
      targetPort: {{ .Values.controller.metrics.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: hume-alerting-controller
    {{- include "hume-alerting.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.operator.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-alerting.fullname" . }}-operator-metrics
  labels:
    {{- include "hume-alerting.labels" . | nindent 4 }}
    app.kubernetes.io/component: alerting-operator-metrics
spec:
  type: {{ .Values.operator.metrics.service.type }}
  ports:
    - port: {{ .Values.operator.metrics.service.port }}
      targetPort: {{ .Values.operator.metrics.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: hume-alerting-operator
    {{- include "hume-alerting.selectorLabels" . | nindent 4 }}
{{- end }}
---
