apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-alerting.fullname" . }}-controller
  labels:
    {{- include "hume-alerting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hume-alerting.fullname" . }}-controller
---
