{{- if .Values.eventstore.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-eventstore-configmap
  labels:
  {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  management.server.port: "7001"
  {{- if .Values.postgresqlEventStore.enabled }}
  spring.datasource.url: "jdbc:postgresql://postgresql-eventstore:{{ .Values.postgresqlEventStore.global.postgresql.auth.servicePort }}/{{ .Values.postgresqlEventStore.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.postgresqlEventStore.global.postgresql.auth.username }}
  spring.datasource.password: {{ .Values.postgresqlEventStore.global.postgresql.auth.password }}
  {{ else }}
  spring.datasource.url: "jdbc:postgresql://{{ .Values.customEventstorePostgresql.global.postgresql.auth.hostname }}:{{ .Values.customEventstorePostgresql.global.postgresql.auth.servicePort }}/{{ .Values.customEventstorePostgresql.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.customEventstorePostgresql.global.postgresql.auth.username }}
  {{- end }}
  {{- if .Values.eventstore.metrics.enabled }}
  management.endpoints.web.exposure.include: "health,prometheus,info"
  {{- end }}
{{- end }}
---