{{- if .Values.eventstore.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-eventstore-configmap
  labels:
  {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  spring.datasource.url: "jdbc:postgresql://postgresql-eventstore:{{ .Values.postgresqlEventStore.global.postgresql.auth.servicePort }}/{{ .Values.postgresqlEventStore.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.postgresqlEventStore.global.postgresql.auth.username }}
  spring.datasource.password: {{ .Values.postgresqlEventStore.global.postgresql.auth.password }}
{{- end }}
---