{{- if .Values.ingress.enabled -}}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ include "hume-helm.fullname" . }}-api-ingress
  labels:
    {{- include "hume.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
    - host: {{ .Values.api.app.name }}{{ .Values.ingress.appNameSuffix }}.{{ required "Missing required baseDomain parameter!" .Values.baseDomain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if .Values.ingress.pathType }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "hume-helm.fullname" . }}-api
                port:
                  name: api
{{- end }}