{{- if .Values.media.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-media
  labels:
    app.kubernetes.io/component: hume-media
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.media.service.type }}
  ports:
    - port: {{ .Values.media.port }}
      targetPort: media-http
      protocol: TCP
      name: media-http
  selector:
    app.kubernetes.io/component: hume-media
    {{- include "hume.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.media.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-media-metrics
  labels:
    app.kubernetes.io/component: hume-media
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.media.metrics.service.type }}
  ports:
    - port: {{ .Values.media.metrics.service.port }}
      targetPort: {{ .Values.media.metrics.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: hume-media
    {{- include "hume.selectorLabels" . | nindent 4 }}
{{- end }}