apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra-configmap
  labels:
  {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  {{- if .Values.postgresqlOrchestra.enabled }}
  spring.datasource.url: "jdbc:postgresql://postgresql-orchestra:{{ .Values.postgresqlOrchestra.global.postgresql.auth.servicePort }}/{{ .Values.postgresqlOrchestra.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.postgresqlOrchestra.global.postgresql.auth.username }}
  spring.datasource.password: {{ .Values.postgresqlOrchestra.global.postgresql.auth.password }}
  {{ else }}
  spring.datasource.url: "jdbc:postgresql://{{ .Values.customOrchestraPostgresql.global.postgresql.auth.hostname }}:{{ .Values.customOrchestraPostgresql.global.postgresql.auth.servicePort }}/{{ .Values.customOrchestraPostgresql.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.customOrchestraPostgresql.global.postgresql.auth.username }}
  {{- end }}
  orchestra.storage.engine: db
  {{- if or (.Values.orchestra.cluster.enabled) (gt (.Values.orchestra.deployment.replicas | int | default 1) 1) }}
  orchestra.cluster.enabled: "true"
  orchestra.cluster.node.advertised.host: "${HOSTNAME}-cluster"
  orchestra.instance.mode: "cluster"
  orchestra.cluster.provider: "db"
  orchestra.member.controller.info.enabled: "true"
  orchestra.cluster.nodes.active.number: "{{ .Values.orchestra.deployment.replicas | default 1 }}"
  {{- end }}
  {{- if .Values.orchestra.metrics.enabled }}
  management.endpoints.web.exposure.include: "health,prometheus,info"
  {{- end }}
---