apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra-configmap
  labels:
    app.kubernetes.io/component: hume-orchestra
    {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  orchestra.storage.engine: db
  {{- if .Values.postgresqlOrchestra.enabled }}
  spring.datasource.url: "jdbc:postgresql://postgresql-orchestra:{{ .Values.postgresqlOrchestra.global.postgresql.auth.servicePort }}/{{ .Values.postgresqlOrchestra.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.postgresqlOrchestra.global.postgresql.auth.username }}
  spring.datasource.password: {{ .Values.postgresqlOrchestra.global.postgresql.auth.password }}
  {{ else }}
  spring.datasource.url: "jdbc:postgresql://{{ .Values.customOrchestraPostgresql.global.postgresql.auth.hostname }}:{{ .Values.customOrchestraPostgresql.global.postgresql.auth.servicePort }}/{{ .Values.customOrchestraPostgresql.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.customOrchestraPostgresql.global.postgresql.auth.username }}
  {{- end }}
  {{- if .Values.orchestra.metrics.enabled }}
  management.endpoints.web.exposure.include: "health,prometheus,info"
  {{- end }}
---