apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra-configmap
  labels:
  {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  spring.datasource.url: "jdbc:postgresql://postgresql-orchestra:{{ .Values.postgresqlOrchestra.global.postgresql.auth.servicePort }}/{{ .Values.postgresqlOrchestra.global.postgresql.auth.database }}"
  spring.datasource.username: {{ .Values.postgresqlOrchestra.global.postgresql.auth.username }}
  spring.datasource.password: {{ .Values.postgresqlOrchestra.global.postgresql.auth.password }}
  orchestra.storage.engine: "db"
---