{{- if .Values.eventstore.enabled -}}
{{- if and .Values.eventstore.metrics.enabled .Values.eventstore.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hume-helm.fullname" . }}-eventstore-service-monitor
  labels:
    {{- with .Values.eventstore.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: "eventstore-metrics"
  selector:
    matchLabels:
      obs.hume.k8s.io/component: eventstore-metrics
  endpoints:
  - port: {{ .Values.eventstore.metrics.serviceMonitor.port }}
    path: {{ .Values.eventstore.metrics.serviceMonitor.path }}
    {{- if .Values.eventstore.metrics.serviceMonitor.basicAuth.enabled }}
    basicAuth:
      password:
        name: {{ .Values.eventstore.metrics.serviceMonitor.basicAuth.secretName }}
        key: password
      username:
        name: {{ .Values.eventstore.metrics.serviceMonitor.basicAuth.secretName }}
        key: username
    {{- end }}
{{- end -}}
{{- end -}}