apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-web
  labels:
    app.kubernetes.io/component: hume-web
    {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/component: hume-web
    {{- include "hume.selectorLabels" . | nindent 4 }}
