{{- if .Values.orchestra.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra
  labels:
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orchestra.service.type }}
  ports:
    - port: {{ .Values.orchestra.port }}
      targetPort: orchestra
      protocol: TCP
      name: orchestra
  selector:
    app: {{ include "hume-helm.fullname" . }}-orchestra
{{- end }}
---
{{- if .Values.orchestra.enabled -}}
{{- if .Values.orchestra.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra-metrics
  labels:
    {{- include "hume.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestra-metrics
spec:
  type: {{ .Values.orchestra.metrics.service.type }}
  ports:
    - port: {{ .Values.orchestra.metrics.service.port }}
      targetPort: {{ .Values.orchestra.metrics.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "hume-helm.fullname" . }}-orchestra
{{- end }}
{{- end }}
{{- if .Values.orchestra.webhooks.enabled }}
# add one service per pod as we want to be able to target a specific pod's service
---
{{ range $podIndex := until (.Values.orchestra.deployment.replicas | int | default 1) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra-webhook-{{ $podIndex }}
  labels:
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orchestra.webhooks.service.type }}
  ports:
    - port: {{ .Values.orchestra.port }}
      targetPort: webhook
      protocol: TCP
      name: orchestra-webhook-{{ $podIndex }}
  selector:
    app: {{ include "hume-helm.fullname" . }}-orchestra-{{ $podIndex }}
{{- end}}
{{ end -}}