{{- if .Values.eventstore.enabled -}}
{{- if and .Values.eventstore.metrics.enabled .Values.eventstore.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hume-helm.fullname" . }}-eventstore-service-monitor
  labels:
    {{- with .Values.eventstore.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: "eventstore-metrics"
  selector:
    matchLabels:
      app.kubernetes.io/component: eventstore-metrics
  endpoints:
  - port: {{ .Values.eventstore.metrics.serviceMonitor.port }}
    path: {{ .Values.eventstore.metrics.serviceMonitor.path }}
{{- end -}}
{{- end -}}