{{ range $podIndex := until (.Values.orchestra.deployment.replicas | int | default 1) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" $ }}-orchestra-{{ $podIndex }}
  labels:
    {{- include "hume.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.orchestra.service.type }}
  ports:
    - port: {{ $.Values.orchestra.port }}
      targetPort: orchestra
      protocol: TCP
      name: orchestra
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "hume-helm.fullname" $ }}-orchestra-{{ $podIndex }}
---
{{ end -}}