apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-web
  labels:
    {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app: {{ include "hume-helm.fullname" . }}-web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-api
  labels:
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: {{ include "hume-helm.fullname" . }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra
  labels:
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orchestra.service.type }}
  ports:
    - port: {{ .Values.orchestra.port }}
      targetPort: orchestra
      protocol: TCP
      name: orchestra
  selector:
    app: {{ include "hume-helm.fullname" . }}-orchestra
