{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hume-helm.serviceAccountName" . }}
  labels:
    {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
