{{- if .Values.orchestra.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra
  labels:
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orchestra.service.type }}
  ports:
    - port: {{ .Values.orchestra.port }}
      targetPort: orchestra
      protocol: TCP
      name: orchestra
  selector:
    app: {{ include "hume-helm.fullname" . }}-orchestra
{{- end }}
---
{{- if .Values.orchestra.enabled -}}
{{- if .Values.orchestra.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-orchestra-metrics
  labels:
    {{- include "hume.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestra-metrics
spec:
  type: {{ .Values.orchestra.metrics.service.type }}
  ports:
    - port: {{ .Values.orchestra.metrics.service.port }}
      targetPort: {{ .Values.orchestra.metrics.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "hume-helm.fullname" . }}-orchestra
{{- end }}
{{- end }}
---
{{- if .Values.orchestra.webhooks.enabled -}}
{{ $sumPods := ( .Values.orchestra.deployment.replicas | int | default 1) }}
{{- range $index := until $sumPods }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" $ }}-orchestra-webhook-{{ $index }}
  labels:
    {{- include "hume.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.orchestra.webhooks.service.type }}
  ports:
    - port: {{ $.Values.orchestra.webhooks.port }}
      targetPort: webhook
      protocol: TCP
      name: orchestra-webhook-{{ $index }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "hume-helm.fullname" $ }}-orchestra-{{ $index }}
---
{{- end }}
{{- end }}