apiVersion: v1
kind: Service
metadata:
  name: {{ include "hume-helm.fullname" . }}-api
  labels:
    {{- include "hume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: {{ include "hume-helm.fullname" . }}-api