apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-web-configmap
  labels:
  {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  {{ if .Values.ingress.enabled }}
  HUME_API_URL: "{{ .Values.ingress.protocol.scheme }}://{{ .Values.api.app.name }}{{ .Values.ingress.appNameSuffix }}.{{ required "Missing required baseDomain parameter!" .Values.baseDomain }}"
  {{ else }}
  HUME_API_URL: "http://localhost:{{ .Values.api.port }}"
  {{ end }}
  {{- if .Values.keycloak.enabled}}
  KEYCLOAK_ENABLED: 'true'
  {{- if .Values.ingress.enabled }}
  KEYCLOAK_URL: "{{ .Values.ingress.protocol.scheme }}://{{ .Values.keycloak.app.name }}{{ .Values.ingress.appNameSuffix }}.{{ required "Missing required baseDomain parameter!" .Values.baseDomain }}"
  {{ else }}
  KEYCLOAK_URL: "http://localhost:{{ .Values.keycloak.service.ports.http }}"
  {{ end }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm }}
  KEYCLOAK_CLIENT: {{ .Values.keycloak.client }}
  {{- end}}
---