{{- if .Values.web.extraHeaders }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hume-helm.fullname" . }}-web-extra-headers-configmap
  labels:
    app.kubernetes.io/component: hume-web
    {{- include "hume.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
data:
  extra-headers.conf: |
      {{- range .Values.web.extraHeaders }}
      {{ . }}
      {{- end }}
{{- end }}