apiVersion: v2
name: hume-alerting
description: A Helm chart for Kubernetes
type: application
version: "2.16.7.0"
appVersion: "2.16.7"
dependencies:
  - name: postgresql
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlAlertingController
  - name: postgresql
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlAlertingOperator
  - name: kafka
    version: 18.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.internal.enabled