apiVersion: v2
name: hume-alerting
description: A Helm chart for Kubernetes
type: application
version: "2.17.2"
appVersion: "2.17.2"
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlAlertingController
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlAlertingOperator
  - name: kafka
    version: 18.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.internal.enabled