apiVersion: v2
name: hume-alerting
description: A Helm chart for Kubernetes
type: application
icon: https://s3.eu-west-1.amazonaws.com/www-graphaware-com.infra.graphaware.com/favicon.ico
version: "2.27.0-SNAPSHOT"
appVersion: "2.27.0-SNAPSHOT"
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: postgresqlAlertingController
    condition: postgresqlAlertingController.enabled
  - name: postgresql
    version: 12.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: postgresqlAlertingOperator
    condition: postgresqlAlertingOperator.enabled
  - name: kafka
    version: 22.1.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kafka.internal.enabled
