apiVersion: v2
name: hume-alerting
description: A Helm chart for Kubernetes
type: application
icon: https://s3.eu-west-1.amazonaws.com/www-graphaware-com.infra.graphaware.com/favicon.ico
version: 2.28.1-SNAPSHOT
appVersion: 2.28.1-SNAPSHOT
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: oci://docker.graphaware.com/public/bitnami
    alias: postgresqlAlertingController
    condition: postgresqlAlertingController.enabled
  - name: postgresql
    version: 12.1.5
    repository: oci://docker.graphaware.com/public/bitnami
    alias: postgresqlAlertingOperator
    condition: postgresqlAlertingOperator.enabled
  - name: kafka
    version: 22.1.4
    repository: oci://docker.graphaware.com/public/bitnami
    condition: kafka.internal.enabled
