apiVersion: v2
name: hume
home: https://www.graphaware.com
version: "2.16.0"
appVersion: "2.16.0-SNAPSHOT"
type: application
icon: https://s3.eu-west-1.amazonaws.com/graphaware.com/favicon.ico
keywords:
  - hume
  - neo4j
  - graphs
description: "Helm Chart for GraphAware Hume - A Graph-Powered Insights Engine"
dependencies:
    - name: postgresql
      version: 11.8.1
      repository: https://charts.bitnami.com/bitnami
      alias: postgresqlCore
    - name: keycloak
      version: 10.0.0
      repository: https://charts.bitnami.com/bitnami
      alias: keycloak
      condition: keycloak.enabled
    - name: neo4j
      version: "4.3.6"
      repository: "https://docker.graphaware.com/chartrepo/mirror"
      condition: neo4j.enabled
    - name: hume-alerting
      version: "0.1.4"
      repository: "https://docker.graphaware.com/chartrepo/public" 
      condition: alerting.enabled