apiVersion: v2
name: hume
home: https://www.graphaware.com
version: "2.16.0"
appVersion: "2.16.0-SNAPSHOT"
type: application
icon: https://s3.eu-west-1.amazonaws.com/graphaware.com/favicon.ico
keywords:
  - graphaware
  - hume
  - neo4j
  - graph
description: "Helm Chart for GraphAware Hume - A Graph-Powered Insights Engine"
dependencies:
    - name: postgresql
      version: 11.9.1
      repository: https://charts.bitnami.com/bitnami
      alias: postgresqlCore
    - name: keycloak
      version: 10.1.0
      repository: https://charts.bitnami.com/bitnami
      alias: keycloak
      condition: keycloak.enabled
    - name: neo4j-standalone
      version: "4.4.11"
      repository: "https://helm.neo4j.com/neo4j"
      condition: neo4j.enabled
      alias: neo4j
    - name: hume-alerting
      version: "0.1.4"
      repository: "https://docker.graphaware.com/chartrepo/public" 
      condition: alerting.enabled