apiVersion: v2
name: hume
home: https://www.graphaware.com
version: "2.27.0-RC1"
appVersion: "2.27.0-RC1"
type: application
icon: https://s3.eu-west-1.amazonaws.com/www-graphaware-com.infra.graphaware.com/favicon.ico
keywords:
  - graphaware
  - hume
  - neo4j
  - graph
description: "Helm Chart for GraphAware Hume - A Graph-Powered Insights Engine"
dependencies:
    - name: postgresql
      version: 12.1.5
      repository: oci://docker.graphaware.com/public/bitnami
      alias: postgresqlCore
      condition: postgresqlCore.enabled
    - name: postgresql
      version: 12.1.5
      repository: oci://docker.graphaware.com/public/bitnami
      alias: postgresqlOrchestra
      condition: postgresqlOrchestra.enabled
    - name: postgresql
      version: 12.1.5
      repository: oci://docker.graphaware.com/public/bitnami
      alias: postgresqlEventStore
      condition: postgresqlEventStore.enabled
    - name: postgresql
      version: 12.1.5
      repository: oci://docker.graphaware.com/public/bitnami
      alias: postgresqlMedia
      condition: postgresqlMedia.enabled
    - name: keycloak
      version: 13.1.1
      repository: oci://docker.graphaware.com/public/bitnami
      alias: keycloak
      condition: keycloak.internal.enabled
    - name: hume-alerting
      version: "2.27.0-RC1"
      repository: "oci://docker.graphaware.com/public"
      condition: alerting.enabled
