apiVersion: v2
name: hume
home: https://www.graphaware.com
version: "2.18.0-SNAPSHOT"
appVersion: "2.18.0"
type: application
icon: https://s3.eu-west-1.amazonaws.com/www-graphaware-com.infra.graphaware.com/favicon.ico
keywords:
  - graphaware
  - hume
  - neo4j
  - graph
description: "Helm Chart for GraphAware Hume - A Graph-Powered Insights Engine"
dependencies:
    - name: postgresql
      version: 12.1.5
      repository: https://charts.bitnami.com/bitnami
      alias: postgresqlCore
      condition: postgresqlCore.enabled
    - name: postgresql
      version: 12.1.5
      repository: https://charts.bitnami.com/bitnami
      alias: postgresqlOrchestra
      condition: postgresqlOrchestra.enabled
    - name: postgresql
      version: 12.1.5
      repository: https://charts.bitnami.com/bitnami
      alias: postgresqlEventStore
      condition: postgresqlEventStore.enabled
    - name: keycloak
      version: 13.1.1
      repository: https://charts.bitnami.com/bitnami
      alias: keycloak
      condition: keycloak.enabled
    - name: neo4j-standalone
      version: "4.4.17"
      repository: "https://helm.neo4j.com/neo4j"
      condition: neo4j.enabled
      alias: neo4j
    - name: hume-alerting
      version: "2.18.0-SNAPSHOT"
      repository: "https://docker.graphaware.com/chartrepo/public" 
      condition: alerting.enabled